name: Secure CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test || true


  sast-sonarqube:
    name: SonarCloud Scan
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io


   dast-zap:
    name: OWASP ZAP Scan
    runs-on: ubuntu-latest
    needs: sast-sonarqube

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run OWASP ZAP Scan (Passive)
        uses: zaproxy/action-baseline@v0.10.0
        with:
          target: "https://www.google.com"
          fail_action: false
